org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric - pile du serveur MMO Haute Capitale
minecraft_version=1.21.11
loader_version=0.19.5
loom_version=1.17.20

# Mod (convention .bN : monter le numero a chaque jar livre)
version=0.1.0+1.21.11.b3
group=net.hautecapitale

# Dependances
fabric_api_version=0.141.6+1.21.11
geckolib_version=5.4.5
